"""
Cache configuration for Gandalf MCP server.
"""

# Import cache constants from unified constants file
from config.constants import (
    CACHE_ROOT_DIR,
    CONVERSATION_CACHE_DIR,
    FILE_CACHE_DIR,
    GIT_CACHE_DIR,
    CONVERSATION_CACHE_FILE,
    CONVERSATION_CACHE_METADATA_FILE,
    CONVERSATION_CACHE_TTL_HOURS,
    CONVERSATION_CACHE_TTL_SECONDS,
    CONTEXT_CACHE_TTL_SECONDS,
    CONTEXT_GIT_CACHE_TTL,
    MCP_CACHE_TTL,
    CONVERSATION_CACHE_MIN_SIZE,
    CONVERSATION_CACHE_MAX_SIZE_MB,
)
