"""Context intelligence and file scoring configuration constants."""

from typing import Final

from src.config.constants.limits import (
    VALIDATION_FILE_SIZE_ACCEPTABLE_MAX,
    VALIDATION_FILE_SIZE_OPTIMAL_MAX,
)

CONTEXT_KEYWORD_MAX_COUNT: Final[int] = 15
CONTEXT_MAX_FILES_TO_CHECK: Final[int] = 50
CONTEXT_MIN_EXTENSIONS_BEFORE_DEEP_SCAN: Final[int] = 3
CONTEXT_KEYWORDS_QUICK_LIMIT: Final[int] = 10

# File size constants from limits.py to avoid duplication
CONTEXT_FILE_SIZE_ACCEPTABLE_MAX: Final[int] = VALIDATION_FILE_SIZE_ACCEPTABLE_MAX
CONTEXT_FILE_SIZE_OPTIMAL_MAX: Final[int] = VALIDATION_FILE_SIZE_OPTIMAL_MAX
CONTEXT_TOP_FILES_COUNT: Final[int] = 20

# Token optimization configuration
TOKEN_OPTIMIZATION_MAX_RESPONSE_SIZE: Final[int] = 16_000
TOKEN_OPTIMIZATION_CONTENT_TRUNCATION_LIMIT: Final[int] = 1_000
TOKEN_OPTIMIZATION_SUMMARY_MODE_THRESHOLD: Final[int] = 10
TOKEN_OPTIMIZATION_MAX_CONTEXT_KEYWORDS: Final[int] = 15
TOKEN_OPTIMIZATION_MAX_TOOL_RESULT_FIELDS: Final[int] = 8

# Activity-based weight constants
ACTIVITY_SCORE_MAX_DURATION: Final[int] = 30  # days
CONTEXT_FILE_SIZE_PENALTY_THRESHOLD: Final[int] = 100_000  # 100KB

# Base weights
ACTIVE_FILE_WEIGHT: Final[float] = 5.0
IMPORT_NEIGHBOR_WEIGHT: Final[float] = 3.0
RECENT_EDIT_WEIGHT: Final[float] = 4.0
CURSOR_ACTIVITY_WEIGHT: Final[float] = 2.0

# Scoring thresholds and multipliers
CURSOR_ACTIVITY_WEIGHT_MULTIPLIER: Final[float] = 1.5
CURSOR_ACTIVITY_SCORE_THRESHOLD: Final[float] = 0.1
CURSOR_ACTIVITY_POSITION_WEIGHT: Final[float] = 0.3
CURSOR_ACTIVITY_RECENT_WEIGHT: Final[float] = 0.7

RECENT_EDIT_HOURS_THRESHOLD: Final[int] = 24
RECENT_EDIT_WEIGHT_MULTIPLIER: Final[float] = 2.0
RECENT_EDIT_SCORE_THRESHOLD: Final[float] = 0.2
RECENT_EDIT_TIME_WEIGHT: Final[float] = 0.5

IMPORT_NEIGHBOR_SCORE_THRESHOLD: Final[float] = 0.15
IMPORT_NEIGHBOR_WEIGHT_MULTIPLIER: Final[float] = 1.8
IMPORT_NEIGHBOR_DEPTH_WEIGHT: Final[float] = 0.2

ACTIVE_FILE_SCORE_THRESHOLD: Final[float] = 0.3
ACTIVE_FILE_WEIGHT_MULTIPLIER: Final[float] = 3.0

# File tools configuration
HIGH_PRIORITY_DISPLAY_LIMIT: Final[int] = 50
MEDIUM_PRIORITY_DISPLAY_LIMIT: Final[int] = 15
LOW_PRIORITY_DISPLAY_LIMIT: Final[int] = 10
TOP_FILES_DISPLAY_LIMIT: Final[int] = 15
MAX_FILES_LIMIT: Final[int] = 10_000
