"""Windsurf-specific conversation patterns and indicators."""

# Windsurf-specific conversation patterns
WINDSURF_CONVERSATION_PATTERNS = {
    "chat",
    "conversation",
    "message",
    "session",
    "dialog",
    "ai",
    "assistant",
    "windsurf",
    "cascade",
    "codeium",
    "history",
    "input",
    "output",
    "response",
    "query",
    "prompt",
    "brain",
    "config",
}

WINDSURF_STRONG_CONVERSATION_INDICATORS = {
    "messages",
    "content",
    "text",
    "input",
    "output",
    "prompt",
    "response",
    "user",
    "assistant",
    "ai",
    "human",
    "question",
    "answer",
    "chat",
    "conversation",
    "brain",
    "config",
    "session",
    "entries",
}

WINDSURF_FALSE_POSITIVE_INDICATORS = {
    "workbench",
    "panel",
    "view",
    "container",
    "storage",
    "settings",
    "layout",
    "editor",
    "terminal",
    "debug",
    "extension",
    "plugin",
    "theme",
    "color",
    "font",
    "keybinding",
    "menu",
    "toolbar",
    "statusbar",
    "sidebar",
    "explorer",
    "search",
}

WINDSURF_CONTENT_KEYS = {
    "messages",
    "content",
    "text",
    "input",
    "output",
    "body",
    "message",
    "entries",
    "data",
}

WINDSURF_MESSAGE_INDICATORS = {
    "message",
    "content",
    "text",
    "user",
    "assistant",
    "conversation",
    "chat",
}
